environment:
  nodejs_version: "12"

install:
  - ps: Install-Product node 16
  - yarn --network-timeout 600000


build_script:
  - yarn install --ignore-engines
  - yarn build

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'
  # - node_modules -> appveyor.yml, **\package.json, yarn.lock
  # - '%LOCALAPPDATA%\Yarn -> appveyor.yml, **\package.json, yarn.lock'

build: off

branches:
  except:
    - docs