export default [
  {
    title: 'Home',
    route: 'home',
    icon: 'HomeIcon',
    resource: 'auth',
    action: 'read',
  },
  {
    title: 'User List',
    route: 'user-list',
    icon: 'UserIcon',
    resource: 'user',
    action: 'manage',
  },
  {
    title: 'Create Project',
    route: 'project-register',
    icon: 'BookIcon',
    resource: 'client-project',
    action: 'manage',
  },
  {
    title: 'List Project',
    route: 'project-list',
    icon: 'BookIcon',
    resource: 'project',
    action: 'manage',
  },
  {
    title: 'List Client Project',
    route: 'client-project-list',
    icon: 'BookIcon',
    resource: 'client-project',
    action: 'manage',
  },
  {
    title: 'Master Data',
    icon: 'SettingsIcon',
    resource: 'master',
    action: 'manage',
    children: [
      {
        title: 'Master City',
        route: 'city-list',
        icon: 'MapIcon',
        resource: 'master',
        action: 'manage',
      },
      {
        title: 'Master Province',
        route: 'province-list',
        icon: 'MapIcon',
        resource: 'master',
        action: 'manage',
      },
      {
        title: 'Master Building Type',
        route: 'building-type-list',
        icon: 'MapIcon',
        resource: 'master',
        action: 'manage',
      },
      {
        title: 'Admin Data',
        route: 'admin-data',
        icon: 'MapIcon',
        resource: 'master',
        action: 'manage',
      },
    ],
  },
]
